SET DEFINE OFF;
Insert into ABSENCE
   (ABSEN_DATE, PERIOD_DAYS, EMPLOYEE_EMP_ID)
 Values
   (TO_DATE('12/24/2021 1:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 4, 1);
Insert into ABSENCE
   (ABSEN_DATE, PERIOD_DAYS, EMPLOYEE_EMP_ID)
 Values
   (TO_DATE('12/28/2021', 'MM/DD/YYYY'), 2, 1);
Insert into ABSENCE
   (ABSEN_DATE, PERIOD_DAYS, EMPLOYEE_EMP_ID)
 Values
   (TO_DATE('12/29/2021', 'MM/DD/YYYY'), 2, 3);
Insert into ABSENCE
   (ABSEN_DATE, PERIOD_DAYS, EMPLOYEE_EMP_ID)
 Values
   (TO_DATE('12/7/2021', 'MM/DD/YYYY'), 1, 4);
COMMIT;
