SET DEFINE OFF;
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (5000, 1, 1, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (4500, 2, 1, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (3500, 3, 1, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (4000, 4, 1, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (2, 1, 3, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (1.5, 2, 3, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (2.5, 3, 3, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (1, 2, 4, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (2500, 4, 2, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (3, 4, 3, TO_DATE('11/30/2021', 'MM/DD/YYYY'), 11);
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (2000, 1, 1, TO_DATE('8/30/2021', 'MM/DD/YYYY'), 8);
Insert into EMP_COMPEN
   (COMPEN_VALUE, EMPLOYEE_EMP_ID, COMPENSATION_COMPEN_ID, COMPEN_DATE, IN_MONTH)
 Values
   (488, 1, 1, TO_DATE('11/30/2021', 'MM/DD/YYYY'), 11);
COMMIT;
