SET DEFINE OFF;
Insert into EMP_DISCOUNT
   (DISC_VALUE, EMPLOYEE_EMP_ID, DISCOUNT_DISC_ID, DISC_DATE, IN_MONTH)
 Values
   (3, 4, 1, TO_DATE('9/30/2021', 'MM/DD/YYYY'), 9);
Insert into EMP_DISCOUNT
   (DISC_VALUE, EMPLOYEE_EMP_ID, DISCOUNT_DISC_ID, DISC_DATE, IN_MONTH)
 Values
   (10, 1, 1, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_DISCOUNT
   (DISC_VALUE, EMPLOYEE_EMP_ID, DISCOUNT_DISC_ID, DISC_DATE, IN_MONTH)
 Values
   (5, 2, 1, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_DISCOUNT
   (DISC_VALUE, EMPLOYEE_EMP_ID, DISCOUNT_DISC_ID, DISC_DATE, IN_MONTH)
 Values
   (7, 3, 1, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_DISCOUNT
   (DISC_VALUE, EMPLOYEE_EMP_ID, DISCOUNT_DISC_ID, DISC_DATE, IN_MONTH)
 Values
   (7.5, 4, 1, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_DISCOUNT
   (DISC_VALUE, EMPLOYEE_EMP_ID, DISCOUNT_DISC_ID, DISC_DATE, IN_MONTH)
 Values
   (2000, 3, 2, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_DISCOUNT
   (DISC_VALUE, EMPLOYEE_EMP_ID, DISCOUNT_DISC_ID, DISC_DATE, IN_MONTH)
 Values
   (3000, 1, 2, TO_DATE('12/29/2021', 'MM/DD/YYYY'), 12);
Insert into EMP_DISCOUNT
   (DISC_VALUE, EMPLOYEE_EMP_ID, DISCOUNT_DISC_ID, DISC_DATE, IN_MONTH)
 Values
   (1500, 2, 2, TO_DATE('8/30/2021', 'MM/DD/YYYY'), 8);
COMMIT;
