SET DEFINE OFF;
Insert into PUNISHMENT
   (PUNISH_ID, EMPLOYEE_EMP_ID, VALUE_IN_MONTH, PUNISH_DATE, FOR_N_MONTHS)
 Values
   (2, 1, 500, TO_DATE('9/29/2021', 'MM/DD/YYYY'), 2);
Insert into PUNISHMENT
   (PUNISH_ID, EMPLOYEE_EMP_ID, VALUE_IN_MONTH, PUNISH_DATE, FOR_N_MONTHS)
 Values
   (1, 1, 4000, TO_DATE('12/28/2021', 'MM/DD/YYYY'), 2);
Insert into PUNISHMENT
   (PUNISH_ID, EMPLOYEE_EMP_ID, VALUE_IN_MONTH, PUNISH_DATE, FOR_N_MONTHS)
 Values
   (3, 2, 900, TO_DATE('12/28/2021', 'MM/DD/YYYY'), 2);
Insert into PUNISHMENT
   (PUNISH_ID, EMPLOYEE_EMP_ID, VALUE_IN_MONTH, PUNISH_DATE, FOR_N_MONTHS)
 Values
   (4, 3, 2500, TO_DATE('8/30/2021', 'MM/DD/YYYY'), 3);
COMMIT;
